### ISSUE TITLE
Dont update tubes List if they has been changed

### ISSUE THREAD

**Issue by uapixart** [gongled/zbx_beanstalkd#1]
Script discovery not update tubes list, maybe you must delete next rows for always update list:
getTubesList() {
    **if [[ ! -f "$BEANSTALK_TUBES_LIST" ]] ; then**
        saveTubesList "`fetchTubesList`"
    **fi**
    tubesList=`cat "$BEANSTALK_TUBES_LIST"`
    echo "$tubesList"
}

**Comment by gongled** [comment]
Oh, it seems to be a bug. Thank you for this issue. Fixed (#2).
